adc_cfg:
  quantization_bitwidth: 8
  voltage_max: 255
  voltage_min: 0
input_dac_cfg:
  quantization_bitwidth: 2
  voltage_max: 255
  voltage_min: 0
laser_cfg:
  optical_gain: 0.1
mrr_cfg:
  mrr_fsr_nm: 16.1
  mrr_k2: 0.03
  mrr_loss_dB: 0.39
mzm_cfg:
  mzm_loss_DB: 1.2
  voltage_max: 255.0
  voltage_min: 0.0
  y_branch_loss_DB: 0.3
pd_cfg:
  pd_GHZ: 5.0
  pd_T: 300.0
  pd_dark_current_pA: 0.0
  pd_resistance: 50.0
  pd_responsivity: 1.0
  pd_rin_DBCHZ: 0.0
tia_cfg:
  gain: 1.0
weight_dac_cfg:
  quantization_bitwidth: 8
  voltage_max: 255
  voltage_min: 0
