adc_cfg:
  quantization_bitwidth: 64
  voltage_max: 1.0
  voltage_min: 0.0
input_dac_cfg:
  quantization_bitwidth: 64
  voltage_max: 1.0
  voltage_min: 0.0
laser_cfg:
  optical_gain: 1.0 # Identity
mrr_cfg:
  mrr_fsr_nm: 16.1
  mrr_k2: 0.03
  mrr_loss_dB: 0.0 # No loss
mzm_cfg:
  mzm_loss_DB: 0.0
  voltage_max: 1.0
  voltage_min: 0.0
  y_branch_loss_DB: 0.0
pd_cfg:
  pd_GHZ: 0.0 # No shot noise via this nor any thermal noise
  pd_T: 0 # Temperature of 0 => no thermal noise
  pd_dark_current_pA: 0.0
  pd_resistance: 50.0
  pd_responsivity: 1.0
  pd_rin_DBCHZ: 0.0
tia_gain: 1.0 # Identity
weight_dac_cfg:
  quantization_bitwidth: 64
  voltage_max: 1.0
  voltage_min: 0.0
